[tool.poetry]
name = "kotano-gendiff"
version = "0.2.0"
description = "Find difference between two files"
authors = ["kotano"]

packages = [
    { include = "gendiff" },
]

[tool.poetry.scripts]
gendiff = "gendiff.main:main"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
